name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        version: [13, 14, 15]
        xcode-select: ["xcode", "clt"]
      fail-fast: false

    name: Build (macos-${{ matrix.version }}${{ matrix.xcode-select == 'clt' && ', Command Line Tools' || '' }})

    runs-on: macos-${{ matrix.version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Switch to Xcode Command Line Tools
      if: ${{ matrix.xcode-select == 'clt' }}
      run: sudo xcode-select --switch /Library/Developer/CommandLineTools

    - name: Build
      run: make enable

